// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtontlronxidpzccmngq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10b250bHJvbnhpZHB6Y2NtbmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxODYwMjcsImV4cCI6MjA0OTc2MjAyN30.vzUGYcW1sagVKiFcIGlPk7asBbbifOwIEpvLwIOc2oA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);